### ISSUE TITLE
Single GPU training

### ISSUE THREAD

**Issue by kgiannakelos** [Thinklab-SJTU/DCL_RetinaNet_Tensorflow#1]
Hello and thanks for your hard work! 

I want to train the models with a single gpu. Could you please give me some analogy between multi_gpu training and single_gpu configurations? 

Looking on [this](https://github.com/Thinklab-SJTU/DCL_RetinaNet_Tensorflow/blob/main/libs/configs/DOTA1.0/dcl/cfgs_res152_dota_dcl_v1.py) configuration i have the following hyperparameters i need to change
```
SAVE_WEIGHTS_INTE = 27000*4 
LR = 5e-4
BATCH_SIZE = 1
MAX_ITERATION = SAVE_WEIGHTS_INTE*20
```

Could you please give some insights as to what values should those hyperparameters change into? Are there any other hyperparameters i need to change to support single gpu training?

Thank you!

**Comment by yangxue0827** [comment]
SAVE_WEIGHTS_INTE = 27000*3
